# basic options
title: Omics
author: Krishna 
#email: your-email@domain.com
description: Working on Ipythin notebook
github_username: krishnakantsingh14

# Build settings
markdown: kramdown
theme: minima

#theme: jekyll-theme-cayman
